CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    
    id_number VARCHAR(50),
    
    fname VARCHAR(100) NOT NULL,
    mname VARCHAR(100),
    lname VARCHAR(100) NOT NULL,
    picture VARCHAR(512),

    address VARCHAR(500),
    city VARCHAR(255),


    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,

    last_login DATETIME,


    suspended TINYINT(1) DEFAULT 0,
    deleted TINYINT(1) DEFAULT 0,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE user_role (
    id INT PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(255) NOT NULL,
    description TEXT,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE question (
    id INT PRIMARY KEY AUTO_INCREMENT,
    question_text TEXT,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);