


CREATE TABLE grade_levels (
    id INT PRIMARY KEY AUTO_INCREMENT,
    level INT NOT NULL
);

CREATE TABLE grade_sections (
    id INT PRIMARY KEY AUTO_INCREMENT,
    grade_level_id INT NOT NULL,
    section_name VARCHAR(255) NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (grade_level_id) REFERENCES grade_levels(id)
);

CREATE TABLE subjects (
    id INT PRIMARY KEY AUTO_INCREMENT,

    subject_name VARCHAR(255) NOT NULL,
    description TEXT,

    grade_level_id INT NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (grade_level_id) REFERENCES grade_levels(id)
);

CREATE TABLE topics (
    id INT PRIMARY KEY AUTO_INCREMENT,

    title VARCHAR(255) NOT NULL,
    description TEXT,

    subject_id INT NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

