
CREATE TABLE school_year (
    id INT PRIMARY KEY AUTO_INCREMENT,
    start_year INT NOT NULL,
    end_year INT NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE grade_levels (
    id INT PRIMARY KEY AUTO_INCREMENT,
    level INT NOT NULL
);

CREATE TABLE grade_sections (
    id INT PRIMARY KEY AUTO_INCREMENT,
    grade_level_id INT NOT NULL,
    section_name VARCHAR(255) NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (grade_level_id) REFERENCES grade_levels(id)
);
